// <auto-generated />
using System;
using Devagram.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devagram.Migrations
{
    [DbContext(typeof(DevagramContext))]
    [Migration("20231214043710_TabelaSeguidores")]
    partial class TabelaSeguidores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devagram.Models.Seguidor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("idUsuarioSeguido")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuarioSeguidor")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idUsuarioSeguido");

                    b.HasIndex("idUsuarioSeguidor");

                    b.ToTable("Seguidores");
                });

            modelBuilder.Entity("Devagram.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Devagram.Models.Seguidor", b =>
                {
                    b.HasOne("Devagram.Models.Usuario", "UsuarioSeguido")
                        .WithMany()
                        .HasForeignKey("idUsuarioSeguido");

                    b.HasOne("Devagram.Models.Usuario", "UsuarioSeguidor")
                        .WithMany()
                        .HasForeignKey("idUsuarioSeguidor");

                    b.Navigation("UsuarioSeguido");

                    b.Navigation("UsuarioSeguidor");
                });
#pragma warning restore 612, 618
        }
    }
}
